### ISSUE TITLE
Timeout error?? 

### ISSUE THREAD

**Issue by TrentBrick** [elkebir-group/GISAIDScraper#4]
It looks like a timeout error is being thrown:

`(node:11384) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at /Users/trentonbricken/GISAIDScraper/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
    at async FrameManager.waitForFrameNavigation (/Users/trentonbricken/GISAIDScraper/node_modules/puppeteer/lib/FrameManager.js:139:19)
    at async Frame.waitForNavigation (/Users/trentonbricken/GISAIDScraper/node_modules/puppeteer/lib/FrameManager.js:414:12)
    at async Page.waitForNavigation (/Users/trentonbricken/GISAIDScraper/node_modules/puppeteer/lib/Page.js:692:12)
    at async /Users/trentonbricken/GISAIDScraper/scrape.js:34:3
  -- ASYNC --
    at Frame.<anonymous> (/Users/trentonbricken/GISAIDScraper/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.waitForNavigation (/Users/trentonbricken/GISAIDScraper/node_modules/puppeteer/lib/Page.js:692:49)
    at Page.<anonymous> (/Users/trentonbricken/GISAIDScraper/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/trentonbricken/GISAIDScraper/scrape.js:34:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:11384) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11384) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by TrentBrick** [comment]
Changing the url login to `await page.goto('https://platform.gisaid.org/epi3/frontend')` gets me through the login but the rest of the navigation does not work. I get another timeout error without collecting any sequences.

**Comment by crosstj** [comment]
Similar error here, 
(node:18726) UnhandledPromiseRejectionWarning: TimeoutError: Navigation timeout of 30000 ms exceeded
    at /Users/tjcross/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21
    at async FrameManager.waitForFrameNavigation (/Users/tjcross/node_modules/puppeteer/lib/FrameManager.js:139:19)
    at async Frame.waitForNavigation (/Users/tjcross/node_modules/puppeteer/lib/FrameManager.js:414:12)
    at async Page.waitForNavigation (/Users/tjcross/node_modules/puppeteer/lib/Page.js:692:12)
    at async /Users/tjcross/scrape.js:34:3
  -- ASYNC --
    at Frame.<anonymous> (/Users/tjcross/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.waitForNavigation (/Users/tjcross/node_modules/puppeteer/lib/Page.js:692:49)
    at Page.<anonymous> (/Users/tjcross/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/tjcross/scrape.js:34:14
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18726) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18726) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
